name: Generate ASCII Artworks

on: push

jobs: 
    ascii_jobs: 
        runs-on: ubuntu-latest 
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Using Shell Script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
 
        